name: elsa-mkdocs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip>=23.0
  - pip:
      - mkdocs>=1.5.3
      - mkdocs-material>=9.5.0
      - mkdocs-static-i18n>=1.2.0
      - mkdocs-glightbox>=0.3.7
      - mkdocs-minify-plugin>=0.8.0
      - mkdocs-redirects>=1.2.1
      - mkdocs-caption
      - pymdown-extensions>=10.7
      - markdown>=3.5.0
      - Pygments>=2.17.0
      - pyyaml>=6.0.1
