site_name: ELSA Integrated Spatial Planning Tool
site_description: User's Guide for the UN Biodiversity Lab Essential Life Support Area (ELSA) Integrated Spatial Planning Tool
site_author: UN Biodiversity Lab Team
site_url: https://undp-unbl.github.io/elsa-documentation/
copyright: Copyright &copy; 2025 UNDP & UNEP-WCMC

# Repository
repo_name: UNDP-UNBL/elsa-documentation
repo_url: https://github.com/UNDP-UNBL/elsa-documentation
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Lato
    code: Inconsolata
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/images/UNBL_FULL_WEBSITE.png
  favicon: assets/images/favicon.ico

# Plugins
plugins:
  - search:
      lang:
        - en
        - es
        - fr
        - pt
        - ru
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            ELSA Tool Documentation: Documentación de la Herramienta ELSA
            Overview: Descripción General
            Tool Purpose and Key Features: Propósito de la Herramienta y Características Clave
            Registration and Access: Registro y Acceso
            Creating a New Analysis: Crear un Nuevo Análisis
            Editing an Analysis: Editar un Análisis
            Running the Optimization: Ejecutar la Optimización
            Viewing Heatmaps: Ver Mapas de Calor
            Downloading Results: Descargar Resultados
            Analyzing Synergies and Trade-offs: Analizar Sinergias y Compromisos
            Citing Maps: Citar Mapas
            Support and Contact: Soporte y Contacto
            Annex 1 - Technical Details: Anexo 1 - Detalles Técnicos
            Annex 2 - Glossary: Anexo 2 - Glosario
            Training Materials: Materiales de Capacitación
            Regional Guidance: Guía Regional
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            ELSA Tool Documentation: Documentation de l'outil ELSA
            Overview: Aperçu
            Tool Purpose and Key Features: À quoi sert l'outil ELSA
            Registration and Access: Inscription et Accès
            Creating a New Analysis: Créer une Nouvelle Analyse
            Editing an Analysis: Modifier une Analyse
            Running the Optimization: Exécuter l'Optimisation
            Viewing Heatmaps: Visualiser les Cartes Thermiques
            Downloading Results: Télécharger les Résultats
            Analyzing Synergies and Trade-offs: Analyser les Synergies et les Compromis
            Citing Maps: Citer les Cartes
            Support and Contact: Soutien et Contact
            Annex 1 - Technical Details: Annexe 1 - Détails Techniques
            Annex 2 - Glossary: Annexe 2 - Glossaire
            Training Materials: Matériel de formation
            Regional Guidance: Orientation régionale
        - locale: pt
          name: Português
          build: true
          nav_translations:
            Home: Início
            ELSA Tool Documentation: Documentação da Ferramenta ELSA
            Overview: Visão Geral
            Tool Purpose and Key Features: Finalidade da Ferramenta e Recursos Principais
            Registration and Access: Registro e Acesso
            Creating a New Analysis: Criar uma Nova Análise
            Editing an Analysis: Editar uma Análise
            Running the Optimization: Executar a Otimização
            Viewing Heatmaps: Visualizar Mapas de Calor
            Downloading Results: Baixar Resultados
            Analyzing Synergies and Trade-offs: Analisar Sinergias e Compensações
            Citing Maps: Citar Mapas
            Support and Contact: Suporte e Contato
            Annex 1 - Technical Details: Anexo 1 - Detalhes Técnicos
            Annex 2 - Glossary: Anexo 2 - Glossário
            Training Materials: Materiais de Treinamento
            Regional Guidance: Orientação Regional
        - locale: ru
          name: Русский
          build: true
          nav_translations:
            Home: Главная
            ELSA Tool Documentation: Документация инструмента ELSA
            Overview: Обзор
            Tool Purpose and Key Features: Назначение инструмента и ключевые функции
            Registration and Access: Регистрация и доступ
            Creating a New Analysis: Создание нового анализа
            Editing an Analysis: Редактирование анализа
            Running the Optimization: Запуск оптимизации
            Viewing Heatmaps: Просмотр тепловых карт
            Downloading Results: Загрузка результатов
            Analyzing Synergies and Trade-offs: Анализ синергии и компромиссов
            Citing Maps: Цитирование карт
            Support and Contact: Поддержка и контакты
            Annex 1 - Technical Details: Приложение 1 - Технические детали
            Annex 2 - Glossary: Приложение 2 - Глоссарий
            Training Materials: Учебные материалы
            Regional Guidance: Региональное руководство
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - caption:

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      toc_depth: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

# Extra CSS and JavaScript
extra_css:
  - assets/css/elsa-custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra Configuration
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UNDP-UNBL
      name: UNDP-UNBL on GitHub
    - icon: fontawesome/solid/globe
      link: https://www.unbiodiversitylab.org
      name: UN Biodiversity Lab
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/UNDP-UNBL/elsa-documentation/issues/new" target="_blank" rel="noopener">creating an issue</a>.

# Navigation Structure
nav:
  - Home: index.md
  - ELSA Tool Documentation:
      - elsa/index.md
      - Overview: elsa/01_overview.md
      - Tool Purpose and Key Features: elsa/02_tool_purpose.md
      - Registration and Access: elsa/03_registration.md
      - Creating a New Analysis: elsa/04_creating_analysis.md
      - Editing an Analysis: elsa/05_editing_analysis.md
      - Running the Optimization: elsa/06_running_optimization.md
      - Viewing Heatmaps: elsa/07_viewing_heatmaps.md
      - Downloading Results: elsa/08_downloading_results.md
      - Analyzing Synergies and Trade-offs: elsa/09_analyse_synergies.md
      - Citing Maps: elsa/10_citing_maps.md
      - Support and Contact: elsa/11_support.md
      - Annex 1 - Technical Details: elsa/12_annex1.md
      - Annex 2 - Glossary: elsa/13_annex2.md
  